version: '3'
services:
  docai-rails:
    build:
      context: .
    restart: always
    ports:
      - "9292:9292"
    command: bundle exec puma -e development -C config/puma.rb
    volumes:
      - .:/docai-rails
    platform: linux/amd64
  # worker:
  #   build: .
  #   command: bundle exec sidekiq -e production -c 5 -C config/sidekiq.yml
  #   env_file: .env
  #   environment:
  #     RAILS_ENV: production
